import '../styles/globals.css';
import Head from 'next/head';
import React from 'react';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<Head>
				<title>Hey There</title>
			</Head>
			<body>{children}</body>
		</html>
	);
}
